### ISSUE TITLE
Garbage collector

### ISSUE THREAD

**Issue by Alex2D** [JackM36/Eazy-Sound-Manager#12]
Hi! After reading the message about the memory leak, I downloaded the version from the github. And that's what the profiler showed... 
Only one source of music plays, nothing more, but the garbage collector does not calm down ... :) (Assetstore version -the same picture) 
PS Sorry for googletranslate :)  
![2018-08-23_14-17-07](https://user-images.githubusercontent.com/22461667/44513629-b20e4e80-a6df-11e8-8423-38691884a2d4.png)

**Comment by JackM36** [comment]
Could you please try the updated version and let me know if you still have problems?
