### ISSUE TITLE
Avoid use of null audio source when Pause, UnPause or Resume

### ISSUE THREAD

**Issue by FellipePeixoto** [JackM36/Eazy-Sound-Manager#13]
I use these methods when pause the game, but I don't have control of variable audioSource. To solve this, I add a verification on Pause, UnPause and Resume. An example on line 979:
```
if (audioSource)
{
      audioSource.Pause();
      paused = true;
}
```

**Comment by JackM36** [comment]
Eazy Sound Manager was just updated. Please check the new version and let me know if you still have issues.
