### ISSUE TITLE
Error happen when load scene.

### ISSUE THREAD

**Issue by arumogina** [JackM36/Eazy-Sound-Manager#15]
When  EazySoundManager.PrepareMusic is used,  Error happen with SceneManager.LoadScene().
 
Log:

> KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.Int32,Hellmade.Sound.Audio].get_Item (Int32 key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:561)
Hellmade.Sound.EazySoundManager.RemoveNonPersistAudio (System.Collections.Generic.Dictionary`2 audioDict) (at Assets/Support/Eazy-Sound-Manager-master/Assets/Hellmade/Eazy Sound Manager/Scripts/EazySoundManager.cs:232)
Hellmade.Sound.EazySoundManager.OnSceneLoaded (Scene scene, LoadSceneMode mode) (at Assets/Support/Eazy-Sound-Manager-master/Assets/Hellmade/Eazy Sound Manager/Scripts/EazySoundManager.cs:128)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (Scene scene, LoadSceneMode mode) (at C:/buildslave/unity/build/Runtime/Export/SceneManager/SceneManager.cs:122)

**Comment by arumogina** [comment]
I can move scene by destroying EazyManagerSound Object before SceneManager.LoadScene().

like the following

Destroy(GameObject.Find("EazySoundManager"));
SceneManager.LoadScene();

**Comment by JackM36** [comment]
@arumogina

**Comment by JackM36** [comment]
@arumogina Check the last commit, it should solve your issue.

**Comment by arumogina** [comment]
That issue has been solved.
Thank you,

**Comment by JackM36** [comment]
@dogukanerkut Thanks for letting me know. It must have slipped my mind to update it. Will do so ASAP

**Comment by JackM36** [comment]
@dogukanerkut I have just updated the package!
