### ISSUE TITLE
Exceptions when setting ignoreDuplicateMusic = true

### ISSUE THREAD

**Issue by Kruemelkatze** [JackM36/Eazy-Sound-Manager#7]
Hi!
Thanks for this great tool! It is exactly what I was looking for! But I ran into a bunch of problems when setting the ignoreDuplicateMusic property to true.

### 1) NullReferenceException when setting it to true before first usage
When setting `SoundManager.ignoreDuplicateMusic = true;` in a custom script I use for audio management (I tried placing it in `Start,Awake,OnEnable`), and playing music by ` SoundManager.PlayMusic(...)`, I get following exception:

`NullReferenceException: Object reference not set to an instance of an object
EazyTools.SoundManager.SoundManager.PlayMusic (UnityEngine.AudioClip clip, System.Single volume, System.Boolean loop, System.Boolean persist, System.Single fadeInSeconds, System.Single fadeOutSeconds, System.Single currentMusicfadeOutSeconds, UnityEngine.Transform sourceTransform) (at Assets/Eazy Tools/Sound Manager/Scripts/SoundManager.cs:478)
EazyTools.SoundManager.SoundManager.PlayMusic (UnityEngine.AudioClip clip, System.Single volume, System.Boolean loop, System.Boolean persist) (at Assets/Eazy Tools/Sound Manager/Scripts/SoundManager.cs:439)`

I looked at the code - this happens because the static field `musicAudio` is accessed before calling `Init()`.

I did **not** add the script to the scene (as being written in your installation instructions), therefore the `Awake` function (which calls `Init()`) is not called. For now, i fixed(?) this by accessing the SoundManager instance (and therefore triggering Init()) with this:

 ```cs
var unusedGO = SoundManager.gameobject;
SoundManager.ignoreDuplicateMusic = true; //Has to be set after, as it get's overriden by Init()
```

### 2) MissingReferenceException when trying to play music that has been played before
When using the fix described above and trying to play an AudioClip with `SoundManager.PlayMusic(clip)` that I already played before, I get this exception:
`MissingReferenceException: The object of type 'AudioSource' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
EazyTools.SoundManager.SoundManager.PlayMusic (UnityEngine.AudioClip clip, System.Single volume, System.Boolean loop, System.Boolean persist, System.Single fadeInSeconds, System.Single fadeOutSeconds, System.Single currentMusicfadeOutSeconds, UnityEngine.Transform sourceTransform) (at Assets/Eazy Tools/Sound Manager/Scripts/SoundManager.cs:481)
EazyTools.SoundManager.SoundManager.PlayMusic (UnityEngine.AudioClip clip, System.Single volume, System.Boolean loop, System.Boolean persist) (at Assets/Eazy Tools/Sound Manager/Scripts/SoundManager.cs:439)`

I keep the AudioClip in a Dictionary on my script and do not call any functions on it. I only get it from the Dict and pass it to the SoundManager. This works perfectly fine when not setting ignoreDuplicateMusic!

### Is ignoreDuplicateMusic even supposed to be used?
In this case i just keep track of the current track myself. :)

**Comment by Kruemelkatze** [comment]
Is there any update on these issues? Or did I miss anything? :)

**Comment by JackM36** [comment]
Forgive me for forgetting to get back to you.

Yes, ignoreDuplicateMusic is supposed to be used when needed :)

The issues you are reffering to should be resolved in the last update (a few months ago). Please let me know if you encounter any problems again.

However, we are also preparing a big update that will eliminate such issues altogether.

**Comment by JackM36** [comment]
The update is now live and should resolve your problems. Please give it a try and open a new issue if you still have problems.
