### ISSUE TITLE
Issue with playing short sounds

### ISSUE THREAD

**Issue by myloran** [JackM36/Eazy-Sound-Manager#8]
When playing sound you set starting volume to 0 and on Update() change it. But when a sound is short(20 ms), it can be played on 0 volume before the first Update() tick occurs.

**Comment by JackM36** [comment]
Such short sounds were not taken into account to be honest, since a sound of 20ms is extremely short.

A check of an Audio's length can be added, and if it is too short, the volume can be immediately set before going into Update. 

However, such cases seem very rare to me.
